name: Setup Project
description: Install dependencies
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        cache: "npm"
    - run: npm ci
      shell: bash
